name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: yarn install --frozen-lockfile

      - run: npx nx workspace-lint

      - run: npx nx format:check

      - run: npx nx affected --target=lint --parallel=3

      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage

      - run: npx nx affected --target=build --parallel=3
